"""add repository_manifests table

Revision ID: 1817b2932ed5
Revises: fe80af10916b
Create Date: 2026-09-22 15:01:55.486480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1817b2932ed5'
down_revision: Union[str, Sequence[str], None] = 'fe80af10916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_manifests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('discovery_engine_version', sa.String(length=32), nullable=False),
    sa.Column('manifest_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_manifests_cache_key'), 'repository_manifests', ['cache_key'], unique=True)
    op.create_index(op.f('ix_repository_manifests_repository_id'), 'repository_manifests', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_manifests_repository_id'), table_name='repository_manifests')
    op.drop_index(op.f('ix_repository_manifests_cache_key'), table_name='repository_manifests')
    op.drop_table('repository_manifests')
    # ### end Alembic commands ###
