"""make review_reports commit_sha and branch nullable

Revision ID: 2a3951898fc9
Revises: b7e3c91a4d2f
Create Date: 2026-09-24 18:06:05.639134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3951898fc9'
down_revision: Union[str, Sequence[str], None] = 'b7e3c91a4d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_reports', 'commit_sha',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('review_reports', 'branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_reports', 'branch',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('review_reports', 'commit_sha',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
