"""add static findings table

Revision ID: 80c9b528e1b8
Revises: 1817b2932ed5
Create Date: 2026-09-22 20:41:32.071702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80c9b528e1b8"
down_revision: str | Sequence[str] | None = "1817b2932ed5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "static_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("finding_id", sa.String(length=16), nullable=False),
        sa.Column("tool", sa.String(length=50), nullable=False),
        sa.Column("file", sa.String(length=4096), nullable=False),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=150), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "head_sha", "finding_id", name="uq_static_finding_repo_sha_finding"),
    )
    op.create_index(op.f("ix_static_findings_head_sha"), "static_findings", ["head_sha"], unique=False)
    op.create_index(op.f("ix_static_findings_repository_id"), "static_findings", ["repository_id"], unique=False)
    op.create_index(op.f("ix_static_findings_tool"), "static_findings", ["tool"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_static_findings_tool"), table_name="static_findings")
    op.drop_index(op.f("ix_static_findings_repository_id"), table_name="static_findings")
    op.drop_index(op.f("ix_static_findings_head_sha"), table_name="static_findings")
    op.drop_table("static_findings")
    # ### end Alembic commands ###
