"""drop orphaned kb tables and add dependency_graphs table

Revision ID: d15650c6ecdb
Revises: 80c9b528e1b8
Create Date: 2026-09-24 14:33:03.504884

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d15650c6ecdb"
down_revision: str | Sequence[str] | None = "80c9b528e1b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dependency_graphs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("graph_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dependency_graphs_cache_key"), "dependency_graphs", ["cache_key"], unique=True)
    op.create_index(op.f("ix_dependency_graphs_repository_id"), "dependency_graphs", ["repository_id"], unique=False)
    # ### end Alembic commands ###

    # Orphaned tables from a deleted, never-committed Knowledge Base effort
    # (source files removed from disk without a downgrade first, so their
    # migration scripts no longer exist for autogenerate to diff against).
    # CASCADE drops handle the FK web between them (kb_symbols <- kb_files,
    # kb_call_sites/kb_edges/kb_entrypoints/etc. <- kb_symbols, ...) without
    # needing to hand-sort 18 tables into dependency order.
    _ORPHANED_KB_TABLES = (
        "kb_co_changes",
        "kb_taint_flows",
        "kb_import_stmts",
        "kb_effects",
        "kb_edges",
        "kb_import_cycles",
        "kb_summaries",
        "kb_stage_runs",
        "kb_secret_spans",
        "kb_communities",
        "kb_orm_models",
        "kb_import_edges",
        "kb_findings",
        "kb_metrics",
        "kb_entrypoints",
        "kb_call_sites",
        "kb_symbols",
        "kb_files",
    )
    for table_name in _ORPHANED_KB_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table_name} CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_call_sites",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("kb_symbol_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("callee_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("receiver_kind", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("col", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kb_symbol_id"], ["kb_symbols.id"], name=op.f("kb_call_sites_kb_symbol_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_call_sites_pkey")),
    )
    op.create_index(op.f("ix_kb_call_sites_kb_symbol_id"), "kb_call_sites", ["kb_symbol_id"], unique=False)
    op.create_table(
        "kb_symbols",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("kb_file_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("stable_id", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("kind", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("qualname", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("parent_qualname", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column("start_line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("end_line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("start_byte", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("end_byte", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("signature", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("returns", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("decorators", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("docstring", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_async", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_generator", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("raises", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("attribute_accesses", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("notable_strings", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("body_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("norm_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("docstring_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("bases", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("scc_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("scc_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["kb_file_id"], ["kb_files.id"], name=op.f("kb_symbols_kb_file_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_symbols_pkey")),
        sa.UniqueConstraint(
            "kb_file_id",
            "qualname",
            "kind",
            name=op.f("uq_kb_symbol_file_qualname_kind"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_kb_symbols_stable_id"), "kb_symbols", ["stable_id"], unique=False)
    op.create_index(op.f("ix_kb_symbols_scc_id"), "kb_symbols", ["scc_id"], unique=False)
    op.create_index(op.f("ix_kb_symbols_norm_hash"), "kb_symbols", ["norm_hash"], unique=False)
    op.create_index(op.f("ix_kb_symbols_kb_file_id"), "kb_symbols", ["kb_file_id"], unique=False)
    op.create_table(
        "kb_entrypoints",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("symbol_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("path", sa.VARCHAR(length=4096), autoincrement=False, nullable=False),
        sa.Column("kind", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("route", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column("method", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column("framework", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
        sa.Column("detail", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_entrypoints_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["kb_symbols.id"], name=op.f("kb_entrypoints_symbol_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_entrypoints_pkey")),
    )
    op.create_index(op.f("ix_kb_entrypoints_repository_id"), "kb_entrypoints", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_entrypoints_kind"), "kb_entrypoints", ["kind"], unique=False)
    op.create_index(op.f("ix_kb_entrypoints_head_sha"), "kb_entrypoints", ["head_sha"], unique=False)
    op.create_table(
        "kb_metrics",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("symbol_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("complexity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("fan_in", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("fan_out", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("pagerank", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("churn", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("reachable", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("hotspot", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("hotspot_parts", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_metrics_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["kb_symbols.id"], name=op.f("kb_metrics_symbol_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_metrics_pkey")),
    )
    op.create_index(op.f("ix_kb_metrics_repository_id"), "kb_metrics", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_metrics_head_sha"), "kb_metrics", ["head_sha"], unique=False)
    op.create_table(
        "kb_findings",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("static_finding_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tool", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("rule", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column("severity", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("symbol_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("kb_file_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("line", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("fingerprint", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kb_file_id"], ["kb_files.id"], name=op.f("kb_findings_kb_file_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_findings_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["static_finding_id"],
            ["static_findings.id"],
            name=op.f("kb_findings_static_finding_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["kb_symbols.id"], name=op.f("kb_findings_symbol_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_findings_pkey")),
    )
    op.create_index(op.f("ix_kb_findings_tool"), "kb_findings", ["tool"], unique=False)
    op.create_index(op.f("ix_kb_findings_repository_id"), "kb_findings", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_findings_head_sha"), "kb_findings", ["head_sha"], unique=False)
    op.create_index(op.f("ix_kb_findings_fingerprint"), "kb_findings", ["fingerprint"], unique=False)
    op.create_table(
        "kb_import_edges",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("importer", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("imported", sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
        sa.Column("line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_external", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("type_checking", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_import_edges_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_import_edges_pkey")),
    )
    op.create_index(op.f("ix_kb_import_edges_repository_id"), "kb_import_edges", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_import_edges_importer"), "kb_import_edges", ["importer"], unique=False)
    op.create_index(op.f("ix_kb_import_edges_head_sha"), "kb_import_edges", ["head_sha"], unique=False)
    op.create_table(
        "kb_orm_models",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("symbol_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("framework", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("table_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_orm_models_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["symbol_id"], ["kb_symbols.id"], name=op.f("kb_orm_models_symbol_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_orm_models_pkey")),
    )
    op.create_index(op.f("ix_kb_orm_models_repository_id"), "kb_orm_models", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_orm_models_head_sha"), "kb_orm_models", ["head_sha"], unique=False)
    op.create_table(
        "kb_communities",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("community_key", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("member_symbol_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_symbol_id"],
            ["kb_symbols.id"],
            name=op.f("kb_communities_member_symbol_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_communities_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_communities_pkey")),
    )
    op.create_index(op.f("ix_kb_communities_repository_id"), "kb_communities", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_communities_head_sha"), "kb_communities", ["head_sha"], unique=False)
    op.create_index(op.f("ix_kb_communities_community_key"), "kb_communities", ["community_key"], unique=False)
    op.create_table(
        "kb_secret_spans",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("kb_file_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("start_line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("end_line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rule", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kb_file_id"], ["kb_files.id"], name=op.f("kb_secret_spans_kb_file_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_secret_spans_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_secret_spans_pkey")),
    )
    op.create_index(op.f("ix_kb_secret_spans_repository_id"), "kb_secret_spans", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_secret_spans_head_sha"), "kb_secret_spans", ["head_sha"], unique=False)
    op.create_table(
        "kb_files",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("path", sa.VARCHAR(length=4096), autoincrement=False, nullable=False),
        sa.Column(
            "file_class",
            postgresql.ENUM("SOURCE", "TEST", "CONFIG", "MIGRATION", "GENERATED", "VENDORED", name="kb_file_class"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_files_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_files_pkey")),
        sa.UniqueConstraint(
            "repository_id",
            "head_sha",
            "path",
            name=op.f("uq_kb_file_repo_sha_path"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_kb_files_repository_id"), "kb_files", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_files_head_sha"), "kb_files", ["head_sha"], unique=False)
    op.create_table(
        "kb_stage_runs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("stage", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("OK", "DEGRADED", "SKIPPED", "FAILED", name="kb_stage_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("duration_ms", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cache_hits", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cache_misses", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("coverage", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_stage_runs_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_stage_runs_pkey")),
    )
    op.create_index(op.f("ix_kb_stage_runs_stage"), "kb_stage_runs", ["stage"], unique=False)
    op.create_index(op.f("ix_kb_stage_runs_repository_id"), "kb_stage_runs", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_stage_runs_head_sha"), "kb_stage_runs", ["head_sha"], unique=False)
    op.create_table(
        "kb_summaries",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("summary_key", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("scope", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("scope_id", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("contract", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("contract_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("detail", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("confidence", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("model_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("prompt_version", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("tier", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_summaries_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_summaries_pkey")),
    )
    op.create_index(op.f("ix_kb_summaries_summary_key"), "kb_summaries", ["summary_key"], unique=False)
    op.create_index(op.f("ix_kb_summaries_scope_id"), "kb_summaries", ["scope_id"], unique=False)
    op.create_index(op.f("ix_kb_summaries_repository_id"), "kb_summaries", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_summaries_head_sha"), "kb_summaries", ["head_sha"], unique=False)
    op.create_table(
        "kb_import_cycles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("members", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_import_cycles_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_import_cycles_pkey")),
    )
    op.create_index(op.f("ix_kb_import_cycles_repository_id"), "kb_import_cycles", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_import_cycles_head_sha"), "kb_import_cycles", ["head_sha"], unique=False)
    op.create_table(
        "kb_edges",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("src", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("dst", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("dst_raw", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("confidence", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("resolver", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
        sa.Column("call_site_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("line", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("ambiguous", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["call_site_id"], ["kb_call_sites.id"], name=op.f("kb_edges_call_site_id_fkey"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["dst"], ["kb_symbols.id"], name=op.f("kb_edges_dst_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_edges_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["src"], ["kb_symbols.id"], name=op.f("kb_edges_src_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_edges_pkey")),
    )
    op.create_index(op.f("ix_kb_edges_type"), "kb_edges", ["type"], unique=False)
    op.create_index(op.f("ix_kb_edges_src"), "kb_edges", ["src"], unique=False)
    op.create_index(op.f("ix_kb_edges_repository_id"), "kb_edges", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_edges_head_sha"), "kb_edges", ["head_sha"], unique=False)
    op.create_index(op.f("ix_kb_edges_dst"), "kb_edges", ["dst"], unique=False)
    op.create_table(
        "kb_effects",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("kb_symbol_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("effect", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("origin", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("via_path", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("confidence", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("evidence_line", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kb_symbol_id"], ["kb_symbols.id"], name=op.f("kb_effects_kb_symbol_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_effects_pkey")),
    )
    op.create_index(op.f("ix_kb_effects_kb_symbol_id"), "kb_effects", ["kb_symbol_id"], unique=False)
    op.create_index(op.f("ix_kb_effects_effect"), "kb_effects", ["effect"], unique=False)
    op.create_table(
        "kb_import_stmts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("kb_file_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("module", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("alias", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("line", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("type_checking", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("scoped", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kb_file_id"], ["kb_files.id"], name=op.f("kb_import_stmts_kb_file_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_import_stmts_pkey")),
    )
    op.create_index(op.f("ix_kb_import_stmts_kb_file_id"), "kb_import_stmts", ["kb_file_id"], unique=False)
    op.create_table(
        "kb_taint_flows",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("source_symbol_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("sink_symbol_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("cwe", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("triage", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("triage_tier", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_taint_flows_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["sink_symbol_id"], ["kb_symbols.id"], name=op.f("kb_taint_flows_sink_symbol_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_symbol_id"],
            ["kb_symbols.id"],
            name=op.f("kb_taint_flows_source_symbol_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_taint_flows_pkey")),
    )
    op.create_index(op.f("ix_kb_taint_flows_repository_id"), "kb_taint_flows", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_taint_flows_head_sha"), "kb_taint_flows", ["head_sha"], unique=False)
    op.create_table(
        "kb_co_changes",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repository_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("head_sha", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("kb_file_id_a", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("kb_file_id_b", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("score", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kb_file_id_a"], ["kb_files.id"], name=op.f("kb_co_changes_kb_file_id_a_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["kb_file_id_b"], ["kb_files.id"], name=op.f("kb_co_changes_kb_file_id_b_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repositories.id"], name=op.f("kb_co_changes_repository_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("kb_co_changes_pkey")),
    )
    op.create_index(op.f("ix_kb_co_changes_repository_id"), "kb_co_changes", ["repository_id"], unique=False)
    op.create_index(op.f("ix_kb_co_changes_head_sha"), "kb_co_changes", ["head_sha"], unique=False)
    op.drop_index(op.f("ix_dependency_graphs_repository_id"), table_name="dependency_graphs")
    op.drop_index(op.f("ix_dependency_graphs_cache_key"), table_name="dependency_graphs")
    op.drop_table("dependency_graphs")
    # ### end Alembic commands ###
