"""add ingestion metadata columns to repositories

Revision ID: fe80af10916b
Revises: 7fb7c5dee8ad
Create Date: 2026-09-22 12:06:37.218608

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe80af10916b"
down_revision: str | Sequence[str] | None = "7fb7c5dee8ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Native Postgres enum types aren't auto-created by add_column; create it explicitly first.
    source_type_enum = sa.Enum("GITLAB", name="source_type")
    source_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("repositories", sa.Column("local_path", sa.String(length=4096), nullable=True))
    op.add_column("repositories", sa.Column("head_sha", sa.String(length=64), nullable=True))
    op.add_column("repositories", sa.Column("default_branch", sa.String(length=255), nullable=True))
    op.add_column("repositories", sa.Column("source_type", source_type_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "source_type")
    op.drop_column("repositories", "default_branch")
    op.drop_column("repositories", "head_sha")
    op.drop_column("repositories", "local_path")

    sa.Enum(name="source_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
